window.BEIJING_WECHAT_ENTRIES_META = {
  version: "2026-07-16",
  scope: "北京三甲医院公众号/服务号/小程序入口承接表",
  sourcePolicy: "只收录医院官网公开页面中可核验的微信二维码入口；二维码图片来自官网或由官网二维码解码出的真实 qrPayload 承接，不使用未核验官网 URL 生成假公众号二维码。",
};

window.BEIJING_WECHAT_ENTRIES = {
  pumch: [
    {
      type: "wechat",
      name: "北京协和医院微信入口",
      accountName: "北京协和医院微信",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/dUgLEzbEhGv7rXJw9x1n",
      sourceUrl: "https://www.pumch.cn",
      qrImageUrl: "assets/wechat-qrcodes/pumch-0.jpg",
      qrPayload: "http://weixin.qq.com/r/dUgLEzbEhGv7rXJw9x1n",
      status: "official",
      confidence: "high",
      notes: "官网首页浮层图片标注“协和微信”；原图同时包含“北京协和医院微信”和“协和医生说微信”，qrPayload 对应左侧北京协和医院微信。",
    },
  ],
  beijing_hospital: [
    {
      type: "wechat",
      name: "北京医院官方微信入口",
      accountName: "北京医院官方微信",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/A0i4oLPE8u6NrffD9x0R",
      sourceUrl: "https://www.bjhmoh.cn/index.php?r=archives/default/wx&t=1784195792",
      qrImageUrl: "https://www.bjhmoh.cn/static/img/weixin.jpg",
      qrPayload: "http://weixin.qq.com/r/A0i4oLPE8u6NrffD9x0R",
      status: "official",
      confidence: "high",
      notes: "官网顶部“官方微信”页面内公开二维码。",
    },
  ],
  pkufh: [
    {
      type: "wechat",
      name: "北大医院微信服务号入口",
      accountName: "北京大学第一医院 微信服务号",
      accountType: "service_account",
      canRegister: "likely",
      profileUrl: "http://weixin.qq.com/r/CXUOFh7ExUO6rVp19yAb",
      sourceUrl: "https://www.pkufh.com",
      qrImageUrl: "https://www.pkufh.com/Content/Areas/Hospitals/images/Main/boot/fwh.jpg",
      qrPayload: "http://weixin.qq.com/r/CXUOFh7ExUO6rVp19yAb",
      status: "official",
      confidence: "high",
      notes: "官网页脚二维码区标注“北京大学第一医院 微信服务号”。",
    },
    {
      type: "wechat",
      name: "北大医院微信订阅号入口",
      accountName: "北京大学第一医院 微信订阅号",
      accountType: "subscription_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/ZEjE3HTElSnqrTC-9x12",
      sourceUrl: "https://www.pkufh.com",
      qrImageUrl: "https://www.pkufh.com/Content/Areas/Hospitals/images/Main/boot/gzh.jpg",
      qrPayload: "http://weixin.qq.com/r/ZEjE3HTElSnqrTC-9x12",
      status: "official",
      confidence: "high",
      notes: "官网页脚二维码区标注“北京大学第一医院 微信订阅号”。",
    },
  ],
  pkuph: [
    {
      type: "wechat",
      name: "北大人民医院微信入口",
      accountName: "北京大学人民医院微信",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/vkxRSdjES4U0rZwq9xms",
      sourceUrl: "https://www.pkuph.cn",
      qrImageUrl: "https://www.pkuph.cn/Uploads/Picture/2020/03/09/s5e65fbc46fa3e_206_206_0_2.png",
      qrPayload: "http://weixin.qq.com/r/vkxRSdjES4U0rZwq9xms",
      status: "official",
      confidence: "high",
      notes: "官网浮层标题为“微信”。",
    },
  ],
  puh3: [
    {
      type: "wechat",
      name: "北医三院微信服务号入口",
      accountName: "北医三院微信服务号",
      accountType: "service_account",
      canRegister: "likely",
      profileUrl: "http://weixin.qq.com/r/HkO7o7bE5OubrfLA9xYM",
      sourceUrl: "https://www.puh3.net.cn",
      qrImageUrl: "https://www.puh3.net.cn/images/list16_img2.jpg",
      qrPayload: "http://weixin.qq.com/r/HkO7o7bE5OubrfLA9xYM",
      status: "official",
      confidence: "high",
      notes: "官网页脚二维码区标注“微信服务号”。",
    },
    {
      type: "wechat",
      name: "北医三院微信订阅号入口",
      accountName: "北医三院微信订阅号",
      accountType: "subscription_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/9HXy6g3EOFBHrUmJ9yDm",
      sourceUrl: "https://www.puh3.net.cn",
      qrImageUrl: "https://www.puh3.net.cn/images/list16_img1.jpg",
      qrPayload: "http://weixin.qq.com/r/9HXy6g3EOFBHrUmJ9yDm",
      status: "official",
      confidence: "high",
      notes: "官网页脚二维码区标注“微信订阅号”。",
    },
  ],
  bj_tongren: [
    {
      type: "wechat",
      name: "北京同仁医院微信入口",
      accountName: "北京同仁医院微信",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/bE04ICTEmHnnrWBD9xh_",
      sourceUrl: "https://www.trhos.com",
      qrImageUrl: "https://www.trhos.com/Sites/Uploaded/UserUpLoad/20160627/20160627094645.jpg",
      qrPayload: "http://weixin.qq.com/r/bE04ICTEmHnnrWBD9xh_",
      status: "official",
      confidence: "high",
      notes: "官网右侧固定浮层“微信”按钮公开二维码。",
    },
  ],
  bj_chaoyang: [
    {
      type: "wechat",
      name: "北京朝阳医院微信订阅号入口",
      accountName: "北京朝阳医院微信订阅号",
      accountType: "subscription_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/7ExYQNXEGYhmrZEj9xn_",
      sourceUrl: "https://www.bjcyh.com.cn",
      qrImageUrl: "assets/wechat-qrcodes/bj_chaoyang-22.jpg",
      qrPayload: "http://weixin.qq.com/r/7ExYQNXEGYhmrZEj9xn_",
      status: "official",
      confidence: "high",
      notes: "官网入口区标注“微信订阅号”。",
    },
  ],
  xuanwu: [
    {
      type: "wechat",
      name: "宣武医院微信入口",
      accountName: "宣武医院微信",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/-HWIkDnEMGRPrX3z9yDu",
      sourceUrl: "https://www.xwhosp.com.cn",
      qrImageUrl: "assets/wechat-qrcodes/xuanwu-5.jpg",
      qrPayload: "http://weixin.qq.com/r/-HWIkDnEMGRPrX3z9yDu",
      status: "official",
      confidence: "high",
      notes: "官网头部微信浮层及首页“医院微信”区域公开二维码。",
    },
  ],
  jishuitan: [
    {
      type: "wechat",
      name: "北京积水潭医院官方微信入口",
      accountName: "北京积水潭医院官方微信",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/sEgxKZHEQcw_rdVK9x2i",
      sourceUrl: "https://www.jst-hosp.com.cn",
      qrImageUrl: "https://www.jst-hosp.com.cn/Sites/Uploaded/UserUpLoad/20230710/20230710152939.jpg",
      qrPayload: "http://weixin.qq.com/r/sEgxKZHEQcw_rdVK9x2i",
      status: "official",
      confidence: "high",
      notes: "官网页脚二维码列表标注“官方微信”。",
    },
  ],
  fuwai: [
    {
      type: "wechat",
      name: "阜外医院微信入口",
      accountName: "阜外医院微信",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/6nWEnA-EJlJZrUv-9yD4",
      sourceUrl: "https://www.fuwai.com",
      qrImageUrl: "https://www.fuwai.com/Content/Revision/image/code01.png",
      qrPayload: "http://weixin.qq.com/r/6nWEnA-EJlJZrUv-9yD4",
      status: "official",
      confidence: "high",
      notes: "官网右侧工具栏 weixin 浮层公开二维码。",
    },
  ],
  pumc_plastic: [
    {
      type: "wechat",
      name: "八大处整形医院微信入口",
      accountName: "中国医学科学院整形外科医院微信",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/mp/tRHdxR-EHUJirVum90Sn",
      sourceUrl: "https://www.zhengxing.com.cn",
      qrImageUrl: "https://www.zhengxing.com.cn/upload/20251225/1766643988090.jpg",
      qrPayload: "http://weixin.qq.com/r/mp/tRHdxR-EHUJirVum90Sn",
      status: "official",
      confidence: "high",
      notes: "官网页脚微信图标浮层公开二维码。",
    },
  ],
  cicams: [
    {
      type: "wechat",
      name: "医科院肿瘤医院微信入口",
      accountName: "中国医学科学院肿瘤医院微信",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/6ThkfJ7EaMMXrdof9237",
      sourceUrl: "https://www.cicams.ac.cn",
      qrImageUrl: "https://www.cicams.ac.cn/Uploads/Picture/2022/04/14/s6257e84b6569d.jpg",
      qrPayload: "http://weixin.qq.com/r/6ThkfJ7EaMMXrdof9237",
      status: "official",
      confidence: "high",
      notes: "官网 icon-wx 浮层公开二维码。",
    },
  ],
  pkuh6: [
    {
      type: "wechat",
      name: "北大六院微信服务号入口",
      accountName: "北京大学第六医院微信服务号",
      accountType: "service_account",
      canRegister: "likely",
      profileUrl: "http://weixin.qq.com/r/gRPu9sbEK5tUrYKV90aT",
      sourceUrl: "https://www.pkuh6.cn",
      qrImageUrl: "https://www.pkuh6.cn/Sites/Uploaded/UserUpLoad/20250328/20250328111403.png",
      qrPayload: "http://weixin.qq.com/r/gRPu9sbEK5tUrYKV90aT",
      status: "official",
      confidence: "high",
      notes: "官网右侧固定入口标注“微信服务号”。",
    },
    {
      type: "wechat",
      name: "北大六院微信订阅号入口",
      accountName: "北京大学第六医院微信订阅号",
      accountType: "subscription_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/4kPL0-XEGKhnrbGw9xbw",
      sourceUrl: "https://www.pkuh6.cn",
      qrImageUrl: "https://www.pkuh6.cn/Sites/Uploaded/UserUpLoad/20250328/20250328111213.jpg",
      qrPayload: "http://weixin.qq.com/r/4kPL0-XEGKhnrbGw9xbw",
      status: "official",
      confidence: "high",
      notes: "官网右侧固定入口标注“微信订阅号”。",
    },
    {
      type: "wechat",
      name: "北大六院微信小程序入口",
      accountName: "北京大学第六医院小程序",
      accountType: "mini_program",
      canRegister: "yes",
      profileUrl: "https://mp.weixin.qq.com/a/~B1mT2N6Wjl3wVH9dztT8Uw~~",
      sourceUrl: "https://www.pkuh6.cn/Html/News/Articles/101287.html",
      qrImageUrl: "https://www.pkuh6.cn/Sites/Uploaded/Image/2025/12/086390081592593364771489287.jpg",
      qrPayload: "https://mp.weixin.qq.com/a/~B1mT2N6Wjl3wVH9dztT8Uw~~",
      status: "official",
      confidence: "high",
      notes: "官网文章明确“北京大学第六医院微信小程序”可预约挂号、缴费、取消预约。",
    },
  ],
  pkuss: [
    {
      type: "wechat",
      name: "北大口腔医院微信入口",
      accountName: "北京大学口腔医院微信",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/U0Ps9KvEqfbWre_X9xZB",
      sourceUrl: "https://ss.bjmu.edu.cn",
      qrImageUrl: "https://ss.bjmu.edu.cn/Content/Areas/Common/images/main/ipkuss.jpg",
      qrPayload: "http://weixin.qq.com/r/U0Ps9KvEqfbWre_X9xZB",
      status: "official",
      confidence: "high",
      notes: "官网页脚“医院微信”浮层公开二维码。",
    },
  ],
  bjcancer: [
    {
      type: "wechat",
      name: "北大肿瘤医院微信订阅号入口",
      accountName: "北京大学肿瘤医院微信订阅号",
      accountType: "subscription_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/f0MUDFHEhQz6rRVv9xZt",
      sourceUrl: "https://www.bjcancer.org",
      qrImageUrl: "https://www.bjcancer.org/Sites/Uploaded/UserUpLoad/20180727/20180727142318.jpg",
      qrPayload: "http://weixin.qq.com/r/f0MUDFHEhQz6rRVv9xZt",
      status: "official",
      confidence: "high",
      notes: "官网页脚二维码区标注“微信订阅号”；同区服务号图片未能稳定解码，暂未写入。",
    },
  ],
  youan: [
    {
      type: "wechat",
      name: "北京佑安医院微信服务号入口",
      accountName: "北京佑安医院微信服务号",
      accountType: "service_account",
      canRegister: "likely",
      profileUrl: "http://weixin.qq.com/r/fkjUzNDEj43wrZSv9x1s",
      sourceUrl: "https://www.bjyah.com",
      qrImageUrl: "https://www.bjyah.com/Sites/Uploaded/UserUpLoad/20230824/20230824133249.png",
      qrPayload: "http://weixin.qq.com/r/fkjUzNDEj43wrZSv9x1s",
      status: "official",
      confidence: "high",
      notes: "官网页脚二维码区标注“微信服务号”。",
    },
    {
      type: "wechat",
      name: "北京佑安医院微信公众号入口",
      accountName: "北京佑安医院微信公众号",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/G0y7vyXE4_2fKWHcbxmf",
      sourceUrl: "https://www.bjyah.com",
      qrImageUrl: "https://www.bjyah.com/Sites/Uploaded/UserUpLoad/20230824/20230824133402.png",
      qrPayload: "http://weixin.qq.com/r/G0y7vyXE4_2fKWHcbxmf",
      status: "official",
      confidence: "high",
      notes: "官网页脚二维码区标注“微信公众号”。",
    },
  ],
  bch: [
    {
      type: "wechat",
      name: "北京儿童医院微信入口",
      accountName: "北京儿童医院官方微信",
      accountType: "official_account",
      canRegister: "likely",
      profileUrl: "http://weixin.qq.com/r/O0zQyPrEzqexrb6r9xkp",
      sourceUrl: "http://www.bch.com.cn",
      qrImageUrl: "http://www.bch.com.cn/Sites/Uploaded/Image/2020/04/176372272901935619828643879.jpg",
      qrPayload: "http://weixin.qq.com/r/O0zQyPrEzqexrb6r9xkp",
      status: "official",
      confidence: "high",
      notes: "官网首页就医指南区展示手机二维码并提示提前注册；具体挂号闭环仍需微信端确认。",
    },
  ],
  bjogh: [
    {
      type: "wechat",
      name: "北京妇产医院微信服务号入口",
      accountName: "北京妇产医院微信服务号",
      accountType: "service_account",
      canRegister: "likely",
      profileUrl: "http://weixin.qq.com/r/rkO1revEVLYrra-O9xa8",
      sourceUrl: "https://www.bjogh.com.cn",
      qrImageUrl: "assets/wechat-qrcodes/bjogh-13.png",
      qrPayload: "http://weixin.qq.com/r/rkO1revEVLYrra-O9xa8",
      status: "official",
      confidence: "high",
      notes: "官网顶部微信浮窗标题标注“微信服务号”。",
    },
  ],
  bj_stomatological: [
    {
      type: "wechat",
      name: "北京口腔医院微信公众号入口",
      accountName: "北京口腔医院微信公众号",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/lUOzq2fEbzoQrSPI9xaH",
      sourceUrl: "https://www.dentist.org.cn",
      qrImageUrl: "https://www.dentist.org.cn/Content/Areas/Common/images/common/gongzhonghao.png",
      qrPayload: "http://weixin.qq.com/r/lUOzq2fEbzoQrSPI9xaH",
      status: "official",
      confidence: "high",
      notes: "官网页脚二维码区标注“微信公众号”。",
    },
  ],
  bjxk: [
    {
      type: "wechat",
      name: "北京胸科医院微信入口",
      accountName: "北京胸科医院微信",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/bUxJUXLEmC-nrTYy9xl-",
      sourceUrl: "https://www.bjxkyy.cn",
      qrImageUrl: "assets/wechat-qrcodes/bjxk-3.jpg",
      qrPayload: "http://weixin.qq.com/r/bUxJUXLEmC-nrTYy9xl-",
      status: "official",
      confidence: "high",
      notes: "官网首页快捷入口标注“微信”。",
    },
  ],
  anding: [
    {
      type: "wechat",
      name: "北京安定医院微信入口",
      accountName: "北京安定医院微信",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/I0O6okXE2RimrQHB9xYx",
      sourceUrl: "https://www.bjad.com.cn",
      qrImageUrl: "https://www.bjad.com.cn/Sites/Uploaded/UserUpLoad/20181226/20181226091249.jpg",
      qrPayload: "http://weixin.qq.com/r/I0O6okXE2RimrQHB9xYx",
      status: "official",
      confidence: "high",
      notes: "官网右侧微信入口公开二维码。",
    },
  ],
  shouer: [
    {
      type: "wechat",
      name: "儿研所微信入口",
      accountName: "首都儿科研究所附属儿童医院微信",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/aDpRSQHE61yUrUUq9296",
      sourceUrl: "https://www.shouer.com.cn",
      qrImageUrl: "https://www.shouer.com.cn/Uploads/Picture/2022/03/09/s6228611788461.png",
      qrPayload: "http://weixin.qq.com/r/aDpRSQHE61yUrUUq9296",
      status: "official",
      confidence: "high",
      notes: "官网 icon-wx 浮层公开二维码。",
    },
  ],
  wangjing: [
    {
      type: "wechat",
      name: "望京医院微信服务号入口",
      accountName: "望京医院微信服务号",
      accountType: "service_account",
      canRegister: "likely",
      profileUrl: "http://weixin.qq.com/r/lEgwKBjEZUUarVxL9x2G",
      sourceUrl: "https://www.wjhospital.com.cn",
      qrImageUrl: "https://www.wjhospital.com.cn/Sites/Uploaded/UserUpLoad/20221212/20221212141113.jpg",
      qrPayload: "http://weixin.qq.com/r/lEgwKBjEZUUarVxL9x2G",
      status: "official",
      confidence: "high",
      notes: "官网首页快捷入口标注“服务号”。",
    },
    {
      type: "wechat",
      name: "望京医院微信订阅号入口",
      accountName: "望京医院微信订阅号",
      accountType: "subscription_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/7jklPc7EbpMRrYpe92z8",
      sourceUrl: "https://www.wjhospital.com.cn",
      qrImageUrl: "https://www.wjhospital.com.cn/Sites/Uploaded/UserUpLoad/20230117/20230117115128.jpg",
      qrPayload: "http://weixin.qq.com/r/7jklPc7EbpMRrYpe92z8",
      status: "official",
      confidence: "high",
      notes: "官网首页快捷入口标注“订阅号”。",
    },
  ],
  dongzhimen: [
    {
      type: "wechat",
      name: "东直门医院微信服务号入口",
      accountName: "东直门医院微信服务号",
      accountType: "service_account",
      canRegister: "likely",
      profileUrl: "http://weixin.qq.com/r/mp/9TrdxePEdr4Jraem92-n",
      sourceUrl: "https://www.dzmyy.com.cn",
      qrImageUrl: "https://www.dzmyy.com.cn/Sites/Uploaded/UserUpLoad/20260304/20260304092307.jpg",
      qrPayload: "http://weixin.qq.com/r/mp/9TrdxePEdr4Jraem92-n",
      status: "official",
      confidence: "high",
      notes: "官网页脚二维码区标注“微信服务号”。",
    },
    {
      type: "wechat",
      name: "东直门医院微信订阅号入口",
      accountName: "东直门医院微信订阅号",
      accountType: "subscription_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/DHXC2l3EwAC-rRm59yAe",
      sourceUrl: "https://www.dzmyy.com.cn",
      qrImageUrl: "https://www.dzmyy.com.cn/Content/Areas/Common/images/dingyue.jpg",
      qrPayload: "http://weixin.qq.com/r/DHXC2l3EwAC-rRm59yAe",
      status: "official",
      confidence: "high",
      notes: "官网页脚二维码区标注“微信订阅号”。",
    },
  ],
  bj_tcm: [
    {
      type: "wechat",
      name: "北京中医医院微信服务号入口",
      accountName: "北京中医医院微信服务号",
      accountType: "service_account",
      canRegister: "likely",
      profileUrl: "http://weixin.qq.com/r/7EPI0ITEFtlprcCz9xb_",
      sourceUrl: "https://www.bjzhongyi.com",
      qrImageUrl: "https://www.bjzhongyi.com/Uploads/Picture/2019/12/30/s5e0998d1e0085.png",
      qrPayload: "http://weixin.qq.com/r/7EPI0ITEFtlprcCz9xb_",
      status: "official",
      confidence: "high",
      notes: "官网二维码区标注“微信服务号”。",
    },
    {
      type: "wechat",
      name: "北京中医医院微信订阅号入口",
      accountName: "北京中医医院微信订阅号",
      accountType: "subscription_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/W3UDG23ElzDorSl49yBJ",
      sourceUrl: "https://www.bjzhongyi.com",
      qrImageUrl: "https://www.bjzhongyi.com/Uploads/Picture/2019/12/30/s5e099191ced3c.png",
      qrPayload: "http://weixin.qq.com/r/W3UDG23ElzDorSl49yBJ",
      status: "official",
      confidence: "high",
      notes: "官网二维码区标注“微信订阅号”。",
    },
  ],
  cpzxy: [
    {
      type: "wechat",
      name: "昌平区中西医结合医院官方微信入口",
      accountName: "昌平区中西医结合医院官方微信",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/DEgjOxzE-UGCrVhY9x0e",
      sourceUrl: "http://www.btch.edu.cn",
      qrImageUrl: "http://www.btch.edu.cn/images/2019/code02.png",
      qrPayload: "http://weixin.qq.com/r/DEgjOxzE-UGCrVhY9x0e",
      status: "official",
      confidence: "high",
      notes: "官网页脚二维码区标注“官方微信”。",
    },
  ],
  yuquan: [
    {
      type: "wechat",
      name: "玉泉医院微信公众号入口",
      accountName: "玉泉医院微信公众号",
      accountType: "official_account",
      canRegister: "unknown",
      profileUrl: "http://weixin.qq.com/r/Cx0xKZPEr87QrddK90gZ",
      sourceUrl: "http://www.yuquanhosp.com",
      qrImageUrl: "http://www.yuquanhosp.com/Sites/Uploaded/UserUpLoad/20230602/20230602165741.jpg",
      qrPayload: "http://weixin.qq.com/r/Cx0xKZPEr87QrddK90gZ",
      status: "official",
      confidence: "high",
      notes: "官网页脚二维码区标注“微信公众号”。",
    },
  ],
  pkuih: [
    {
      type: "wechat",
      name: "北京大学国际医院微信服务入口",
      accountName: "北京大学国际医院",
      accountType: "service_account",
      canRegister: "yes",
      profileUrl: "https://wechatfwh.pkuih.edu.cn/home/chinese",
      sourceUrl: "https://www.pkuih.edu.cn/guide/appointment-registration.html",
      qrImageUrl: "",
      qrPayload: "",
      status: "official",
      confidence: "medium",
      notes: "医院官网预约挂号指南列出微信公众号渠道；微信服务页提供预约挂号、查看报告、门诊缴费等入口。未生成伪二维码。",
    },
  ],
};
